Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Unexpected exception from plug-in (Execute): VACC.CRM.Sync.Workflow.ProcessSyncItems: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 21.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ErrorCode>-2147220891</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>OperationStatus</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">0</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>SubErrorCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">-2146233088</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <Message>Unexpected exception from plug-in (Execute): VACC.CRM.Sync.Workflow.ProcessSyncItems: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 21.</Message>
  <Timestamp>2015-01-13T04:04:21.9819829Z</Timestamp>
  <InnerFault i:nil="true" />
  <TraceText>

[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.SyncWorkflowExecutionPlugin]
[36d02364-b39a-e411-bf9c-d89d67763d34: ]
Starting sync workflow 'Process Sync Item to external source', Id: 2fd02364-b39a-e411-bf9c-d89d67763d34
Entering CustomActivityStep1_step: process sync Item
Sync workflow 'Process Sync Item to external source' terminated with error 'Unexpected exception from plug-in (Execute): VACC.CRM.Sync.Workflow.ProcessSyncItems: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 21.'

</TraceText>
</OrganizationServiceFault>

